version: 2.1
orbs:
   ruby: circleci/ruby@2.0.1
jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.1-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test

workflows:
  build_and_test:
    jobs:
      - build
